CREATE DATABASE [Test_Invoice] 
GO 

USE [Test_Invoice] 
GO 

SET ANSI_NULLS ON 
GO 

SET QUOTED_IDENTIFIER ON 
GO 

CREATE TABLE [dbo].[CUSTOMERS]( 
[CUSTOMER_ID] [int] IDENTITY(1,1) NOT NULL, 
[CUSTOMER_NAME] [nvarchar](70) NOT NULL, 
[CUSTOMER_ADDRESS] [nvarchar](120) NOT NULL, 
[CUSTOMER_STATUS] [bit] NOT NULL, 
[CUSTOMER_TYPE_ID] [int] NOT NULL, 
CONSTRAINT [PK_CUSTOMERS] PRIMARY KEY CLUSTERED  
( 
[CUSTOMER_ID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO 


SET QUOTED_IDENTIFIER ON 
GO 

CREATE TABLE [dbo].[CUSTOMER_TYPES]( 
[CUSTOMER_TYPE_ID] [int] IDENTITY(1,1) NOT NULL, 
[CUSTOMER_TYPE_DESCRIPTION] [nvarchar](70) NOT NULL, 
CONSTRAINT [PK_CUSTOMER_TYPES] PRIMARY KEY CLUSTERED  
( 
[CUSTOMER_TYPE_ID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO 

SET ANSI_NULLS ON 
GO 

SET QUOTED_IDENTIFIER ON 
GO

CREATE TABLE [dbo].[INVOICES]( 
[INVOICE_ID] [int] IDENTITY(1,1) NOT NULL, 
[CUSTOMER_ID] [int] NOT NULL, 
[INVOICE_TOTAL_ITBIS] [money] NOT NULL, 
[INVOICE_SUBTOTAL] [money] NOT NULL, 
[INVOICE_TOTAL] [money] NOT NULL, 
CONSTRAINT [PK_INVOICES] PRIMARY KEY CLUSTERED  
( 
[INVOICE_ID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO 

SET ANSI_NULLS ON 
GO 

SET QUOTED_IDENTIFIER ON 
GO 

CREATE TABLE [dbo].[INVOICES_DETAILS]( 
[INVOICE_DETAIL_ID] [int] IDENTITY(1,1) NOT NULL, 
[CUSTOMER_ID] [int] NOT NULL, 
[INVOICE_DETAIL_QUANTITY] [int] NOT NULL, 
[INVOICE_DETAIL_PRICE] [money] NOT NULL, 
[INVOICE_DETAIL_TOTAL_ITBIS] [money] NOT NULL, 
[INVOICE_DETAIL_SUBTOTAL] [money] NOT NULL, 
[INVOICE_DETAIL_TOTAL] [money] NOT NULL, 
CONSTRAINT [PK_INVOICES_DETAILS] PRIMARY KEY CLUSTERED  
( 
[INVOICE_DETAIL_ID] ASC 
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,  ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] 
) ON [PRIMARY] 
GO

ALTER TABLE [dbo].[CUSTOMERS] ADD CONSTRAINT [DF_CUSTOMERS_CUSTOMERS_STATUS] DEFAULT ((1)) FOR [CUSTOMERS_STATUS]
GO 

ALTER TABLE [dbo].[CUSTOMERS] ADD CONSTRAINT [DF_CUSTOMERS_CUSTOMER_TYPES] DEFAULT ((1)) FOR  [CUSTOMER_TYPE_ID] 
GO 
ALTER TABLE [dbo].[INVOICES] ADD CONSTRAINT [DF_INVOICES_INVOICE_TOTAL_ITBIS] DEFAULT ((0)) FOR [INVOICE_TOTAL_ITBIS]
GO 

ALTER TABLE [dbo].[INVOICES_DETAILS] ADD CONSTRAINT [DF_INVOICES_DETAILS_INVOICE_DETAIL_TOTAL_ITBIS] DEFAULT ((0)) FOR [INVOICE_DETAIL_QUANTITY] 
GO 

ALTER TABLE [dbo].[CUSTOMERS] WITH CHECK ADD CONSTRAINT [FK_CUSTOMERS_CUSTOMER_TYPES] FOREIGN 
KEY([CUSTOMER_TYPE_ID]) 
REFERENCES [dbo].[CUSTOMER_TYPES] ([CUSTOMER_TYPE_ID]) 
ON UPDATE CASCADE 
GO

ALTER TABLE [dbo].[CUSTOMERS] CHECK CONSTRAINT [FK_CUSTOMERS_CUSTOMER_TYPES] 
GO 

ALTER TABLE [dbo].[INVOICES] WITH CHECK ADD CONSTRAINT [FK_INNVOICES_CUSTOMERS] FOREIGN KEY([CUSTOMER_ID]) REFERENCES [dbo].[CUSTOMERS] ([CUSTOMER_ID]) 
ON UPDATE CASCADE 
ON DELETE CASCADE 
GO 

ALTER TABLE [dbo].[INVOICES] CHECK CONSTRAINT [FK_INNVOICES_CUSTOMERS] 
GO 

ALTER TABLE [dbo].[INVOICES_DETAILS] WITH CHECK ADD CONSTRAINT [FK_INVOICES_DETAILS_INVOICES] FOREIGN  KEY([CUSTOMER_ID]) 
REFERENCES [dbo].[INVOICES] ([INVOICES_ID]) 
ON UPDATE CASCADE 
ON DELETE CASCADE 
GO 

ALTER TABLE [dbo].[INVOICES_DETAILS] CHECK CONSTRAINT [FK_INVOICES_DETAILS_INVOICES] 
GO


